In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
import tensorflow as tf


In [2]:
iris_data = datasets.load_iris()
iris_data.data[:4]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [3]:
iris_data.target[:4]

array([0, 0, 0, 0])

In [4]:
x_variable = np.array(iris_data.data)
y_variable = np.array(iris_data.target)

In [5]:
len(set(y_variable))

3

In [6]:
#one hot encoding
np.eye(len(set(y_variable)))


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
y_variable = np.eye(len(set(y_variable)))[y_variable]
y_variable

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
"""
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.


    N int

        Number of rows in the output.
    M int, optional

        Number of columns in the output. If None, defaults to N.
    k int, optional

        Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
    dtypedata-type, optional

        Data-type of the returned array.
    order{‘C’, ‘F’}, optional

        Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory


------------------
np.eye(2, dtype=int)
array([[1, 0],
       [0, 1]])

np.eye(3, k=1)
array([[0.,  1.,  0.],
       [0.,  0.,  1.],
       [0.,  0.,  0.]])

"""

"\nnumpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)\n\nReturn a 2-D array with ones on the diagonal and zeros elsewhere.\n\n\n    N int\n\n        Number of rows in the output.\n    M int, optional\n\n        Number of columns in the output. If None, defaults to N.\n    k int, optional\n\n        Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.\n    dtypedata-type, optional\n\n        Data-type of the returned array.\n    order{‘C’, ‘F’}, optional\n\n        Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory\n\n\n------------------\nnp.eye(2, dtype=int)\narray([[1, 0],\n       [0, 1]])\n\nnp.eye(3, k=1)\narray([[0.,  1.,  0.],\n       [0.,  0.,  1.],\n       [0.,  0.,  0.]])\n\n"

In [8]:
#normalise x-variable

x_variable = (x_variable - x_variable.min(0))/x_variable.ptp(0)

In [ ]:
"""
numpy.ptp(a, axis=None, out=None, keepdims=<no value>)[source]

Range of values (maximum - minimum) along an axis.

The name of the function comes from the acronym for ‘peak to peak’.
"""

'\nnumpy.ptp(a, axis=None, out=None, keepdims=<no value>)[source]\n\nRange of values (maximum - minimum) along an axis.\n\nThe name of the function comes from the acronym for ‘peak to peak’.\n'

In [9]:
#split data to train and test
np.random.seed(59)
train_size = np.random.choice(len(x_variable), round(len(x_variable)*0.8),replace=False)
test_size = np.array(list(set(range(len(x_variable)))-set(train_size))) ##

In [10]:
train_size, test_size

(array([ 91,  31, 131, 125, 119, 115,  89,  48, 143, 147, 124,  58,  79,
         49,  43,  23, 109,  92,  20, 104,  75, 137, 114, 110,  82, 144,
         61,  47,  28,   0,  27, 133,  71, 149, 100, 112, 108,  19,  30,
        129, 148,  96, 126,  77,   1,  10,  81,  18,  98,   8,  63,  12,
        146,  22,  26, 139,  99,  16,  34,  62,  15,  80,  25, 135, 136,
         56,  24, 134, 142, 117,  94,  13,  65, 123,  88,  46,  60,  85,
          5, 141,  42, 132,  38, 101,  86,  70,   7,  36,  11,  69,   3,
        127, 113, 105, 111,  52,  97, 103,   6,  72,  54,  17, 116,  55,
          9,  37,  78,  21,  59,  84, 138,  35, 120, 106, 145,  39,  44,
         32,   2,  87]),
 array([128, 130,   4, 140,  14,  29,  33,  40,  41,  45,  50,  51,  53,
         57,  64,  66,  67,  68,  73,  74,  76,  83,  90,  93,  95, 102,
        107, 118, 121, 122]))

In [ ]:
"""

random.choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array


    a1-D array-like or int

        If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)
    sizeint or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
    replaceboolean, optional

        Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.
    p1-D array-like, optional

        The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

Returns:

    samplessingle item or ndarray

        The generated random samples

Raises:

    ValueError

        If a is an int and less than zero, if a or p are not 1-dimensional, if a is an array-like of size 0, if p is not a vector of probabilities, if a and p have different lengths, or if replace=False and the sample size is greater than the population size

np.random.choice(5, 3)
array([0, 3, 4])

np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])
array([3, 3, 0]) # random

"""

'\n\nrandom.choice(a, size=None, replace=True, p=None)\n\nGenerates a random sample from a given 1-D array\n\n\n    a1-D array-like or int\n\n        If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)\n    sizeint or tuple of ints, optional\n\n        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.\n    replaceboolean, optional\n\n        Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.\n    p1-D array-like, optional\n\n        The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.\n\nReturns:\n\n    samplessingle item or ndarray\n\n        The generated random samples\n\nRaises:\n\n    ValueError\n\n        If a is an int and less than zero, if a or p are not

In [11]:
x_train = x_variable[train_size]
x_test = x_variable[test_size]
y_train = y_variable[train_size]
y_test = y_variable[test_size]

In [12]:
x_train.shape,x_test.shape

((120, 4), (30, 4))

In [13]:
#define features
feature_size = len(x_train[0])
k=5



In [ ]:
"""
Given a tensor input, this operation inserts a dimension of length 1 at the dimension index axis of input's shape. The dimension index follows Python indexing rules: It's zero-based, a negative index it is counted backward from the end.

This operation is useful to:

    Add an outer "batch" dimension to a single element.
    Align axes for broadcasting.
    To add an inner vector length axis to a tensor of scalars.


image = tf.zeros([10,10,3])

tf.expand_dims(image, axis=0).shape.as_list()
[1,10,10,3]

tf.expand_dims(image, axis=1).shape.as_list()
[10,1,10,3]

"""

In [17]:
expanded_train = tf.expand_dims(x_train,0)
expanded_test = tf.expand_dims(x_test,1)

expanded_train.shape,expanded_test.shape


(TensorShape([1, 120, 4]), TensorShape([30, 1, 4]))

In [33]:
tf.subtract(expanded_train,expanded_test)

<tf.Tensor: shape=(30, 120, 4), dtype=float64, numpy=
array([[[-0.08333333,  0.08333333, -0.16949153, -0.29166667],
        [-0.27777778,  0.25      , -0.69491525, -0.70833333],
        [ 0.41666667,  0.41666667,  0.13559322, -0.04166667],
        ...,
        [-0.33333333,  0.54166667, -0.69491525, -0.83333333],
        [-0.47222222,  0.16666667, -0.72881356, -0.79166667],
        [-0.02777778, -0.20833333, -0.20338983, -0.33333333]],

       [[-0.36111111,  0.08333333, -0.25423729, -0.20833333],
        [-0.55555556,  0.25      , -0.77966102, -0.625     ],
        [ 0.13888889,  0.41666667,  0.05084746,  0.04166667],
        ...,
        [-0.61111111,  0.54166667, -0.77966102, -0.75      ],
        [-0.75      ,  0.16666667, -0.81355932, -0.70833333],
        [-0.30555556, -0.20833333, -0.28813559, -0.25      ]],

       [[ 0.30555556, -0.25      ,  0.54237288,  0.5       ],
        [ 0.11111111, -0.08333333,  0.01694915,  0.08333333],
        [ 0.80555556,  0.08333333,  0.84745763, 

In [ ]:
"""
Broadcasting

https://www.geeksforgeeks.org/how-to-fix-valueerror-operands-could-not-be-broadcast-together-with-shapes/
"""

In [22]:

#manhattan
distance = tf.reduce_sum(tf.abs(tf.subtract(expanded_train,expanded_test)),2)
"""

 Manhattan Distance = | x 1 − x 2 | + | y 1 − y 2 | . An analogous relationship can be defined in a higher-dimensional space. Nearest-neighbor methods have the advantage that they are easy to implement.
 """

In [ ]:
"""
tf.subtract() : Do Element wise subtraction with x & y
It can subtract list, tuple, scaler, TensorFlow variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple."""

In [ ]:
"""


x has a shape of (2, 3) (two rows and three columns):

1 1 1
1 1 1

By doing tf.reduce_sum(x, 0) the tensor is reduced along the first dimension (rows), so the result is [1, 1, 1] + [1, 1, 1] = [2, 2, 2].

By doing tf.reduce_sum(x, 1) the tensor is reduced along the second dimension (columns), so the result is [1, 1] + [1, 1] + [1, 1] = [3, 3].

By doing tf.reduce_sum(x, [0, 1]) the tensor is reduced along BOTH dimensions (rows and columns), so the result is 1 + 1 + 1 + 1 + 1 + 1 = 6 or, equivalently, [1, 1, 1] + [1, 1, 1] = [2, 2, 2], and then 2 + 2 + 2 = 6 (reduce along rows, then reduce the resulted array).
"""


In [23]:
distance

<tf.Tensor: shape=(30, 120), dtype=float64, numpy=
array([[0.62782486, 1.93102637, 1.01059322, ..., 2.40324859, 2.15936911,
        0.77283427],
       [0.90701507, 2.21021657, 0.64806968, ..., 2.68243879, 2.43855932,
        1.05202448],
       [1.59792844, 0.29472693, 2.48634652, ..., 0.32250471, 0.26694915,
        1.86958569],
       ...,
       [1.37594162, 2.67914313, 0.76530132, ..., 3.15136535, 2.90748588,
        1.35428437],
       [0.52306968, 1.54849341, 1.30979284, ..., 2.02071563, 1.77683616,
        0.77919021],
       [1.13370998, 2.43691149, 0.52306968, ..., 2.90913371, 2.66525424,
        1.2787194 ]])>

In [24]:
_,top_k_indices = tf.nn.top_k(tf.negative(distance),k=k)

In [34]:
tf.nn.top_k(tf.negative(distance),k=k)

TopKV2(values=<tf.Tensor: shape=(30, 5), dtype=float64, numpy=
array([[-0.04166667, -0.17584746, -0.18667608, -0.19444444, -0.2113936 ],
       [-0.28083804, -0.30696798, -0.31473635, -0.33333333, -0.41195857],
       [-0.06944444, -0.06944444, -0.10028249, -0.11111111, -0.11417137],
       [-0.14194915, -0.15112994, -0.15583804, -0.16195857, -0.18196798],
       [-0.23752354, -0.25306026, -0.28695857, -0.30084746, -0.30861582],
       [-0.05084746, -0.06167608, -0.06944444, -0.0863936 , -0.11111111],
       [-0.18361582, -0.23917137, -0.25306026, -0.25306026, -0.28083804],
       [-0.04472693, -0.0863936 , -0.11723164, -0.13112053, -0.13418079],
       [-0.3363936 , -0.36111111, -0.43667608, -0.44444444, -0.4613936 ],
       [-0.06944444, -0.08333333, -0.11723164, -0.12806026, -0.13112053],
       [-0.14500942, -0.16666667, -0.17584746, -0.2452919 , -0.29472693],
       [-0.14500942, -0.15889831, -0.18361582, -0.19750471, -0.2113936 ],
       [-0.08333333, -0.15889831, -0.2113936 , -0

In [25]:
top_k_label = tf.gather(y_train,top_k_indices) #get y vals of these data points

In [36]:
tf.gather(y_train,top_k_indices)

<tf.Tensor: shape=(30, 5, 3), dtype=float64, numpy=
array([[[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        

In [28]:
sum_up_predictions = tf.reduce_sum(top_k_label,axis=1)

In [29]:
sum_up_predictions

<tf.Tensor: shape=(30, 3), dtype=float64, numpy=
array([[0., 0., 5.],
       [0., 0., 5.],
       [5., 0., 0.],
       [0., 0., 5.],
       [5., 0., 0.],
       [5., 0., 0.],
       [5., 0., 0.],
       [5., 0., 0.],
       [5., 0., 0.],
       [5., 0., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 4., 1.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 1., 4.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 0., 5.],
       [0., 0., 5.],
       [0., 0., 5.],
       [0., 0., 5.],
       [0., 0., 5.]])>

In [31]:
prediction = tf.argmax(sum_up_predictions, axis=1)

In [32]:
prediction

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 2, 2, 2, 2, 2])>

In [ ]:
"""tf.argmax()
Returns the index with the largest value across axes of a tensor.

tf.math.argmax(
    input,
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)


A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmax(A)  # A[2] is maximum in tensor A


B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 0)
https://www.tensorflow.org/api_docs/python/tf/math/argmax


"""